sudo: required
dist: trusty
language: node_js
node_js:
- stable
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g angular-cli
script:
- ng test --watch=false
deploy:
  provider: heroku
  api_key:
    secure: "BAjXl2c19jYJj+7HZfxwdVrnCHcJBXYyfFySSgV1d3vu/iJmhX1RRmssx0ul4yosGvSdJWW55qDDWCHnIC8AYUAjB15JfUmrWJHmtv50BychjVUe0M0cPgzl2Nt6dBvyWUSnVGBImM//eq91LeEf3472lV4K2bWmYu5qkauPS3shW3KGm+kmzMyWGePDV5PZc/lsdIUybkxGZbzLHVLdr6VgQ5uLrYTuytpRQ4wbrzZ0tmDR6EgTTW1Bis48NL537qLzOXOZv/lLkhfhdu5VwH1BucoxufBhRMXcMfZs4BS5Mqo+21NsMgYxwYI8y/lObmtoS03ESaRuieQTp7JT+cysG7yRqlP9HPZoGoKDENUY5P+eIfCtgeBwMPIqb2HzzaM+KpUbmw7qIZ9cNh/IuEXVgW3mGxkJbyr0px4JdY7JUT42A/ChjpiwXA/95yfC2+WT1lv+qd23fOvA8cL9Lj3jmdkT4nen3AfSRiIWGE0uUABdugzHveGcs51rvwo9FpxFR7RvgVDWwOtv6EATBqaAYAr82ikicU4F6l9YMsG0lQx0hpupZ//axxPcznD2qdd+fCzMK8ZfY1zA0utIrbb+sW/icJOuZnzSacj+6mHyxClLX6Oa4sXVWKS5c0prlp/6n8diyEYcGatkjTls3Lbl281Znyu9V2Hw4IUOGqA="
  app: drillmajor
  on:
    repo: xbexbex/Drillmajor
